### ISSUE TITLE
Session is not starting

### ISSUE THREAD

**Issue by AndrewDryga** [cafebazaar/elixir-cassandra#1]
Hello,

We trying hard to start using your lib, but in our tests session is not starting quick enough and everything fails:

```
     ** (exit) exited in: GenServer.call(Gateway.DB.Cassandra.Session, {:prepare, "  insert into gateway.logs (id, created_at, idempotency_key, ip_address, request)\n    values (?, toTimestamp(now()), ?, ?, ?);\n"}, 5000)
         ** (EXIT) no process
```

**Comment by AndrewDryga** [comment]
Since there are no tests that use Session I guess its not ready to be used?

**Comment by hzamani** [comment]
This package is under heavy development and API may change. Tests and documentation and Ecto adapter will be added in two week.
For now I can say that `Session` is usable:

``` elixir
contact_points = ["some ip", "other ip", ...]
{:ok, cluster} = Cassandra.Cluster.start_link(contact_points)
{:ok, session} = Cassandra.Session.start_link(cluster)

{:ok, prepared} = Cassandra.Session.prepare(session, query)
Cassandra.Session.execute(session, prepared, values: [...])
```

But best way to send requests to Cassandra is through `Cassandra` supervisor, like Quick Start section in README.
