### ISSUE TITLE
`cast` calls should not return :noreply

### ISSUE THREAD

**Issue by AndrewDryga** [cafebazaar/elixir-cassandra#2]
https://github.com/cafebazaar/elixir-cassandra/blob/master/lib/cassandra/session.ex#L198

**Comment by hzamani** [comment]
This is not a cast, is a function which is called in `handle_call` callback.

`handle_cast` callbacks **should** always return a `:noreply` or `:stop`,
[doc](http://elixir-lang.org/docs/stable/elixir/GenServer.html#c:handle_cast/2).

`handle_call` callbacks **can** return `:noreply` when reply is not ready yet and use `GenServer.reply/2` to reply the `call` when result is ready, [doc](http://elixir-lang.org/docs/stable/elixir/GenServer.html#c:handle_call/3).
